# Generated by Django 4.0.4 on 2022-04-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='description',
            field=models.CharField(max_length=25),
        ),
    ]
